### ISSUE TITLE
Access-Control-Allow-Origin on scoreboard api

### ISSUE THREAD

**Issue by bradkendall** [kittycash/scoreboard-api#17]
### Issue:
Scoreboard API isn't working on `kittycash.com` and `staging.kittycash.com`.  It is working from the wallet app.

### Replication steps:
`curl -v -H 'Origin: https://www.kittycash.com' https://staging-api.kittycatscatarat.club/scoreboard/scores/day ; echo`

OR

`curl -v -H 'Origin: https://staging.kittycash.com' https://staging-api.kittycatscatarat.club/scoreboard/scores/day ; echo`

This should return an Access-Control-Allow-Origin header.

### Suggested resolution:

Add the following servers to `ALLOWED_ORIGINS` environment variable:

- https://www.kittycash.com
- https://staging.kittycash.com
- http://127.0.0.1:6148

**Comment by briancaine** [comment]
Fixed.
