### ISSUE TITLE
Nginx 502 Bad Gateway error

### ISSUE THREAD

**Issue by therealssj** [kittycash/scoreboard-api#19]
We seldom get this error when we try to access the game 
<img width="1633" alt="screen shot 2018-05-04 at 9 01 57 pm" src="https://user-images.githubusercontent.com/8619106/39636676-987b3846-4fde-11e8-8807-5c692ea4b7d5.png">

I think this seems to be the reason behind there being no popup to submit the score ( from what I could infer by looking at the console log ) or the game not opening/taking a long time to open in the wallet

**Comment by bradkendall** [comment]
Fixed with PR #21
