### ISSUE TITLE
Configure DB location

### ISSUE THREAD

**Issue by briancaine** [kittycash/scoreboard-api#5]
I need to be able to specify the DB file location based on an environment variable. Or perhaps a command line flag would do.

**Comment by bradkendall** [comment]
Environment variables have already been implemented.  Everything is in PR  https://github.com/kittycash/scoreboard-api/pull/4 

Readme: https://github.com/bradkendall/scoreboard-api/blob/eaa3c6fd2dd91c31f12af3d4dff500dd2b5a3a86/README.md
